org: louisandrew
app: notion-automation
service: notion-automation

frameworkVersion: "2"

useDotenv: true

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  cronHandler:
    handler: handler.run
    environment:
      NOTION_DB_ID: ${env:NOTION_DB_ID}
      NOTION_API_KEY: ${env:NOTION_API_KEY}
    events:
      # 5 AM UTC everyday -> 9 AM Berlin timezone.
      - schedule: cron(0 5 ? * * *)
