org: louisandrew
app: notion-automation
service: notion-automation

frameworkVersion: "2"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  cronHandler:
    handler: handler.run
    events:
      # 5 AM UTC everyday -> 9 AM Berlin timezone.
      - schedule: cron(0 5 ? * * *)
